[build]
target    = "index.html"
public_url = "./"

[[hooks]]
stage = "pre_build"
command = "node_modules/.bin/tailwindcss.cmd"
command_arguments = [
    "-i", "./styles/input.css",
    "-o", "./styles/tailwind.css",
    "--minify"
]

[[copy-dir]]
path = "static"
