[build]
target = "index.html"
dist = "dist"
public_url = "/"

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i", "./styles/input.css",
    "-o", "./styles/tailwind.css",
    "--minify"
]